
- hosts: scaleway.haum.org
  user: microjoe
  roles:
      - role: simple_microservice
        service_name: hms_ping
      - role: simple_microservice
        service_name: hms_logger
        version: v1.1
      - role: simple_microservice
        service_name: hms_irc
        version: v2.5
      - role: simple_microservice
        service_name: hms_spacestatus
        version: v2.1
      - role: simple_microservice
        service_name: hms_agenda
        version: v1.0
      - role: simple_microservice
        service_name: hms_mastodon
        version: v1.2.1
