
- hosts: scaleway.haum.org
  user: microjoe
  roles:
      - role: simple_microservice
        service_name: hms_ping
      - role: simple_microservice
        service_name: hms_logger
      - role: simple_microservice
        service_name: hms_irc
        version: better_irc
      - role: simple_microservice
        service_name: hms_spacestatus
        version: better_irc
